### ISSUE TITLE
Obtaining Flink plan with './bin/flink info' throws ClassCastException

### ISSUE THREAD

**Issue by fhueske** [dataArtisans/cascading-flink#49]
Trying to get the Flink DAG as JSON using `./bin/flink info` failed with this exception:

java.lang.ClassCastException: org.apache.flink.client.program.OptimizerPlanEnvironment cannot be cast to org.apache.flink.client.program.ContextEnvironment
        at com.dataartisans.flink.cascading.planner.FlinkFlowStepJob.internalNonBlockingStart(FlinkFlowStepJob.java:164)
        at cascading.flow.planner.FlowStepJob.blockOnJob(FlowStepJob.java:269)
        at cascading.flow.planner.FlowStepJob.start(FlowStepJob.java:184)
        at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:146)
        at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:48)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by fhueske** [comment]
Fixed with 6b7b4cf014a48b5eefb80ad28135b0cbdb114d53
